# Generated by Django 3.0.4 on 2020-08-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsingle',
            old_name='content',
            new_name='details',
        ),
        migrations.AddField(
            model_name='blogsingle',
            name='comment_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
